 version: '2'
 services:
   db:
     image: postgres
     container_name: db-1
     environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "mysecretpassword"
   web:
     build: .
     command: bash -c "sleep 10 && pip install psycopg2-binary==2.8.6 && python manage.py migrate && python manage.py populate 1000 --reset && python manage.py runserver 0.0.0.0:8000"
     volumes:
       - .:/code
       - .:/var/www/LL1-Academy
     ports:
       - "8000:8000"
     depends_on:
       - db
